apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: fuse-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "REPLACE_WITH_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "REPLACE_WITH_SECRET_KEY"
  AWS_REGION: "us-east-1"
