{{- if .Values.secrets.aws.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.aws.name }}
  namespace: {{ include "fuse-cache.namespace" . }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.aws.secretAccessKey | quote }}
  AWS_REGION: {{ .Values.secrets.aws.region | quote }}
---
{{- end }}
{{- if .Values.secrets.azure.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.azure.name }}
  namespace: {{ include "fuse-cache.namespace" . }}
type: Opaque
stringData:
  AZURE_STORAGE_ACCOUNT: {{ .Values.secrets.azure.account | quote }}
  AZURE_STORAGE_KEY: {{ .Values.secrets.azure.key | quote }}
  AZURE_CONTAINER_NAME: {{ .Values.secrets.azure.container | quote }}
{{- end }}
